### ISSUE TITLE
.

### ISSUE THREAD

**Issue by pvnotpv** [gaurav800/Google-Meet-Bot#1]
.

**Comment by gaurav800** [comment]
Hey,
Thanks for reaching out. Could you tell me more about the problem? If you
aren't able to explain, a short informal video of the would also be
helpful. Does the console develop an error message? May I know what that
message is?

Regards,
Gaurav

**Comment by VikingStudios-Z** [comment]
$ python3 gMeet.py      
                                                                                                                                        1 ⚙
Starting
Login Successfull
Traceback (most recent call last):
  File "/home/vikingstudiosz/Google-Meet-Bot/gMeet.py", line 64, in <module>
    dismiss=WebDriverWait(driver, 30).until(EC.presence_of_element_located((By.CLASS_NAME,'CwaK9' )))
  File "/home/vikingstudiosz/.local/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


Here, after the login succesfull message , then i get this error as the output and the browser does nothing , it just stays at the join now tab.

**Comment by gaurav800** [comment]
Could you try adding 'time.sleep(10)' before line 64? I believe the page
isn't able to load properly on time and thus that is what is causing the
problem.
